=== NguyetHuynh/DataOnTheWeb/json/Restaurant-Passau.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "./Restaurant-Passau.json",
    "title": "Restaurant",
    "description": "A database for restaurant in Passau",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "integer",
                "title": "ID",
                "description": "Identifier for restaurant in this database"
            },
            "name": {
                "type": "string",
                "title": "Name of Restaurant",
                "description": "Name of restaurant"
            },
            "address": {
                "type": "object",
                "title": "Restaurant Address",
                "description": "Address of restaurant",
                "properties": {                    
                    "street": {
                        "type": "string"
                    },
                    "street-number": {
                        "type": "integer"
                    },
                    "post-code": {
                        "type": "string"
                    },
                    "city": {
                        "type": "string"
                    }
                },
                "required": ["street-number", "street", "city"]
            },
            "menu": {
                "type": "array",
                "items":{
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "name": {
                            "type": "string",
                            "description": "Use to classify menu. For instance, this Vegetarian or Beef or Breakfast Menu"
                        },
                        "dish": {
                            "type": "array",
                            "description": "List of dishes in this menu",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "name": {
                                        "type": "string",
                                        "description": "name of dish"
                                    },
                                    "type": {
                                        "type": "string",
                                        "description": "Can get some values like Vegetarian, Breakfast, Beef, ... This value should be familiar with menu's type."
                                    },
                                    "price": {
                                        "type": "number"
                                    },
                                    "ingredient" : {
                                        "type": "array",
                                        "description": "List of ingredients is used to make this dish",
                                        "items": {
                                            "id": "integer",
                                            "name": "string"
                                        }
                                    } 
                                },
                                "required": ["id", "name", "type", "price"] 
                            }
                            
                        }                    
                    },
                    "required": ["name"]
                }                
            }
        },        
        "required": ["id", "name"]
    }
    
}

=== NguyetHuynh/DataOnTheWeb/json/Restaurant-Passau.json
[
    {
        "id": 1,
        "name": "Amazing Factory Grill & Steak House",
        "address": {            
            "street": "Ort",
            "street-number": 9,
            "post-code": "94032",
            "city": "Passau"
        },
        "menu": [
            {
                "id": 1,
                "name": "Vegetarian",
                "dish": [
                    {
                        "id": 1,
                        "name": "Coconut Soup",
                        "type": "Vegetarian",
                        "price": 2.00,
                        "ingredient": [
                            {
                                "id": 1,
                                "name": "Coconut Milk"
                            },
                            {
                                "id": 2,
                                "name": "Mushroom"
                            },
                            {
                                "id": 3,
                                "name": "Carrot"
                            }
                        ]
                    },
                    {
                        "id": 2,
                        "name": "Pizza with Mushroom",
                        "type": "Vegetarian",
                        "price": 9.00,
                        "ingredient":[
                            {
                                "id": 1,
                                "name": "Flour"
                            },
                            {
                                "id": 2,
                                "name": "Mushroom"
                            },
                            {
                                "id": 3,
                                "name": "Mozzarella Cheese"
                            }
                        ]
                    }
                ]
            },
            {
                "id": 2,
                "name": "Beef",
                "dish": [
                    {                        
                        "id": 1,
                        "name": "Goulash",
                        "type": "Beef",
                        "price": 9.00,
                        "ingredient":[
                            {
                                "id": 1,
                                "name": "Beef"
                            },
                            {
                                "id": 2,
                                "name": "Tomato Sauce"
                            },
                            {
                                "id": 3,
                                "name": "Soured Cream"
                            }
                        ]
                    }
                ]
            }
        ]        
    },
    {
        "id": 2,
        "name": "Am Paulusbogen",
        "address": {
            "street": "Rindermarkt",
            "street-number": 2,
            "post-code": "94032",
            "city": "Passau"
        },
        "menu": [
            {
                "id": 1,
                "name": "Breakfast",
                "dish":[
                    {
                        "id": 1,
                        "name": "Potatoes Pancake",
                        "type": "Breakfast",
                        "price": 3.00,
                        "ingredient": [
                            {
                                "id": 1,
                                "name": "Flour"
                            },
                            {
                                "id": 2,
                                "name": "Potato"
                            }
                        ]
                    },
                    {
                        "id": 1,
                        "name": "Honey Waffle",
                        "type": "Breakfast",
                        "price": 5.00,
                        "ingredient": [
                            {
                                "id": 1,
                                "name": "Flour"
                            },
                            {
                                "id": 2,
                                "name": "Honey"
                            }
                        ]
                    }
                ]
            },
            {
                "id": 2,
                "name": "Drink",
                "dish":[
                    {
                        "id": 1,
                        "name": "Cappuccino",
                        "type": "Drink",
                        "price": 3.00,
                        "ingredient": [
                            {
                                "id": 1,
                                "name": "Coffee"
                            },
                            {
                                "id": 2,
                                "name": "Steamed Milk"
                            }
                        ]
                    },
                    {
                        "id": 2,
                        "name": "Lemon Tea",
                        "type": "Drink",
                        "price": 3.00,
                        "ingredient": [
                            {
                                "id": 1,
                                "name": "Tea"
                            },
                            {
                                "id": 2,
                                "name": "Lemon Juice"
                            }
                        ]
                    }
                ]
            }          
        ]
    }
]
